build_ami:
  base_ami_product: com.ubuntu.cloud:server:16.04:amd64
  rootfs_skel_dirs:
    $append: rootfs.skel
  packages:
    $extend:
      - bwa
      - ncbi-blast+
      - csh
      - xvfb
      - x11vnc
      - mysql-client
      - flex
      - bison
      - bison-doc
      - csh
      - python-scipy
      - python-biom-format
      # TODO: libmotif4
  commands:
    $extend:
      - "echo"
