dns:
  private_zone: xb

build_ami:
  base: auto
  rootfs_skel: auto
  packages:
    - iptables-persistent
    - debian-goodies
    - bridge-utils
    - squid-deb-proxy
    - pixz
    - cryptsetup-bin
    - mdadm
    - btrfs-tools
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - htop
    - pydf
    - jq
    - httpie
    - python-pip
    - python-setuptools
    - python3-pip
    - python3-setuptools
    - nfs-common
    - fail2ban
    - awscli
    - emacs24-nox
  commands:
    - "sed -i -e '/disk_setup/ d' /etc/cloud/cloud.cfg"
    - "apt-get remove --yes popularity-contest postfix"
    - "update-grub"
    - "grub-install /dev/xvda"
    - "pip install awscli-cwlogs"
    - "pip3 install keymaker"
    - "keymaker install"
    - "apt-get clean"
    - "apt-get install --yes docker.io || true"
