build_ami:
  rootfs_skel_dirs:
    $append: rootfs.skel
  commands:
    $extend:
      - "apt-key adv --keyserver pool.sks-keyservers.net --recv 1078ECD7 AC40B2F7 58118E89F3A912897C070ADBF76221572C52609D"
      - "echo deb http://apt.arvados.org/ trusty main > /etc/apt/sources.list.d/arvados.list"
      - "echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list"
      - "apt-get update"
      - "apt-get install --yes docker-engine python-arvados-python-client crunch-run arvados-docker-cleaner python-arvados-fuse"
      - "gem install arvados-cli"
