build_ami:
  base: auto
  rootfs_skel: auto
  packages:
    - iptables-persistent
    - debian-goodies
    - bridge-utils
    - squid-deb-proxy
    - pixz
    - cryptsetup-bin
    - mdadm
    - btrfs-tools
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - htop
    - pydf
    - jq
    - httpie
    - python-pip
    - python-setuptools
    - python-virtualenv
    - python3-pip
    - python3-setuptools
    - python3-virtualenv
    - nfs-common
    - fail2ban
    - awscli
    - emacs24-nox
    - byobu
    - keychain
    - colordiff
    - cgmanager-utils
    - unzip
    - nmap
    - build-essential
    - cmake
  commands:
    - "sed -i -e '/disk_setup/ d' /etc/cloud/cloud.cfg"
    - "apt-get remove --yes popularity-contest postfix apport"
    - "sed -i -e '/^PermitRootLogin/ s/.*/PermitRootLogin no/' /etc/ssh/sshd_config"
    - "update-grub"
    - "grub-install /dev/xvda"
    - "pip install awscli-cwlogs"
    - "pip3 install keymaker"
    - "keymaker install"
    - "apt-get clean"
    - "apt-get install --yes docker.io || true"
    - "activate-global-python-argcomplete"

# Name your Route 53 private DNS zone here. If you leave the value as
# null, Aegea will enumerate the private DNS zones in your account,
# and if only one exists, select and use that one. Otherwise, Aegea
# will raise an error.
dns:
  private_zone: null
