# This config file (aegea/default_config.yml) is written to each user's home directory under the path
# ~/.config/aegea/config.yml if that path is not present. Run any aegea command to cause this to happen.
# Once the file is written, you can modify it with your site or user-specific settings.

build_ami:
  base: auto
  rootfs_skel: auto
  packages:
    - language-pack-en
    - iptables-persistent
    - debian-goodies
    - bridge-utils
    - squid-deb-proxy
    - pixz
    - cryptsetup-bin
    - mdadm
    - btrfs-tools
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - libcurl4-openssl-dev
    - htop
    - pydf
    - jq
    - httpie
    - python-dev
    - python-cffi
    - python-pip
    - python-setuptools
    - python-wheel
    - python-virtualenv
    - python3-dev
    - python3-cffi
    - python3-pip
    - python3-setuptools
    - python3-wheel
    - virtualenv
    - nfs-common
    - fail2ban
    - awscli
    - emacs24-nox
    - byobu
    - keychain
    - colordiff
    - cgmanager-utils
    - unzip
    - nmap
    - build-essential
    - cmake
    - libtool
    - autoconf
  commands:
    - "sed -i -e '/cloudconfig/ d' /etc/fstab"
    - "sed -i -e '/^PermitRootLogin/ s/.*/PermitRootLogin no/' /etc/ssh/sshd_config"
    - "update-grub"
    - "grub-install /dev/xvda"
    - "pip install awscli-cwlogs"
    - "pip3 install keymaker"
    - "keymaker install"
    - "activate-global-python-argcomplete"
    - "dpkg-reconfigure debconf -f noninteractive -p critical"
    - "apt-get install --yes docker.io || true"
    - "apt-get remove --yes popularity-contest postfix apport"
    - "apt-get clean"

# Name your Route 53 private DNS zone here. If you leave the value as
# null, Aegea will enumerate the private DNS zones in your account,
# and if only one exists, select and use that one. Otherwise, Aegea
# will raise an error.
dns:
  private_zone: null

ls:
  sort_by: launch_time
  columns:
    - id
    - state
    - instance_type
    - launch_time
    - public_dns_name
    - image_id
    - tags
    - iam_instance_profile

users:
  columns:
    - name
    - user_id
    - create_date
    - password_last_used
    - groups

groups:
  columns:
    - name
    - group_id
    - create_date
    - users

roles:
  columns:
    - name
    - role_id
    - create_date
    - instance_profiles

policies:
  columns:
    - policy_name
    - arn
    - description
    - create_date
    - update_date
    - attachment_count
  sort_by: attachment_count

volumes:
  columns:
    - id
    - size
    - volume_type
    - iops
    - encrypted
    - state
    - create_time
    - attachments
    - availability_zone

snapshots:
  columns:
    - id
    - description
    - volume
    - volume_size
    - state
    - progress
    - encrypted
    - owner_id
    - start_time
    - tags

buckets:
  columns:
    - name
    - creation_date

images:
  columns:
    - id
    - name
    - description
    - creation_date
    - public
    - virtualization_type
    - state
    - tags
  sort_by: creation_date

security_groups:
  columns:
    - id
    - group_name
    - description
    - ip_permissions
    - ip_permissions_egress
    - vpc_id

clusters:
  columns:
    - clusterName
    - clusterArn
    - status
    - registeredContainerInstancesCount
    - runningTasksCount
    - pendingTasksCount

tasks:
  columns:
    - taskArn
    - taskDefinitionArn
    - clusterArn
    - lastStatus
    - desiredStatus
    - createdAt
    - overrides

sirs:
  columns:
    - SpotInstanceRequestId
    - CreateTime
    - SpotPrice
    - LaunchSpecification.InstanceType
    - State
    - Status.Message
    - InstanceId

sfrs:
  columns:
    - SpotFleetRequestId
    - SpotFleetRequestState
    - SpotFleetRequestConfig.TargetCapacity
    - SpotFleetRequestConfig.ExcessCapacityTerminationPolicy
    - SpotFleetRequestConfig.AllocationStrategy
    - CreateTime
    - SpotFleetRequestConfig.ValidFrom
    - SpotFleetRequestConfig.ValidUntil
  sort_by: CreateTime

subnets:
  columns:
    - id
    - vpc_id
    - availability_zone
    - cidr_block
    - default_for_az
    - map_public_ip_on_launch
    - state
    - tags

tables:
  columns:
    - name
    - key_schema
    - attribute_definitions
    - item_count
    - provisioned_throughput
    - creation_date_time
    - table_size_bytes
    - table_status

filesystems:
  columns:
    - Name
    - FileSystemId
    - SizeInBytes
    - CreationTime
    - LifeCycleState
  mount_target_columns:
    - MountTargetId
    - SubnetId
    - IpAddress
    - NetworkInterfaceId
    - tags

billing:
  detailed_billing_reports_bucket: "detailed-billing-reports-{account_id}"
  columns:
    - ProductName
    - UsageType
    - UsageQuantity
    - UsageStartDate
    - UsageEndDate
    - Cost
